fridgefiller/fridgefiller/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import logout_then_login

from lists.views import *
from lists.invitation_views import *
from lists.pantry_views import *
from lists.party_views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # List App
    url(r'^lists/', include('lists.urls')),

    # User's pantry
    url(r'^pantry/$', PantryView.as_view(), name="pantry"),
    url(r'^pantry/(?P<party_id>\d+)', PartyPantryView.as_view(), name="party-pantry"),
    url(r'^pantry/add/item/', AddItemToPantryView.as_view(), name="add-item-to-pantry"),
    url(r'^pantry/edit/item/', EditItemInPantryView.as_view(), name="edit-item-in-pantry"),
    url(r'^pantry/remove/item/', RemoveItemFromPantryView.as_view(), name="remove-item-from-pantry"),

    # Home App
    url(r'^$', include('home.urls')),

    # Django AllAuth
    url(r'^accounts/logout/$', logout_then_login),
    url(r'^accounts/', include('allauth.urls')),

    # Party URLs
    url(r'^parties/', PartiesView.as_view(), name="parties"),
    url(r'^party/(?P<party_id>\d+)', PartyView.as_view(), name="party"),
    url(r'^party/leave', LeavePartyView.as_view(), name="leave-party"),
    url(r'^party/remove/$', RemovePartyView.as_view(), name="remove-party"),
    #url(r'^party/invite', InvitetoParty.as_view(), name="invite-to-party"),
    url(r'^party/create', CreateParty.as_view(), name="create-party"),
    url(r'^party/addlist', AddPartyList.as_view(), name="add-group-list"),
    url(r'^party/removeList', RemoveListFromPartyView.as_view(), name="remove-list-from-party"),
    url(r'^party/addNewList', CreateNewListForPartyView.as_view(), name="create-list-for-party"),
    url(r'^invitations/$', InvitationListView.as_view(), name='invitation_list'),
    url(r'^invitations/invite/$', InvitationCreateView.as_view(), name='invitation_create'),
    url(r'^invitations/(?P<pk>\d+)/$', InvitationDetailView.as_view(), name='invitation_detail'),
    url(r'^invitations/(?P<pk>\d+)/accept$', InvitationAcceptView.as_view(), name='invitation_accept'),
    url(r'^invitations/(?P<pk>\d+)/decline$', InvitationDeclineView.as_view(), name='invitation_decline'),
    url(r'^delete/list/', DeleteListView.as_view(), name="delete-list"),
]

fridgefiller/home/urls.py
from django.conf.urls import url
from views import HomePageView

urlpatterns = [
    url(r'^', HomePageView.as_view(), name='home'),
]

fridgefiller/lists/urls.py
# urls for the list application

from django.conf.urls import url
from . import views
from views import *

urlpatterns = [
    # List URLs
    url(r'^$', ListsView.as_view(), name="lists"),
    url(r'^(?P<list_id>\d+)', ListView.as_view()),
    url(r'^new/$', NewListView.as_view(), name="new-list"),
    url(r'^edit/(?P<list_id>\d+)', EditListView.as_view()),
    url(r'^new/item/', NewItemView.as_view(), name="new-item"),
    url(r'^remove/item/', RemoveItemFromListView.as_view(), name="remove-item"),
    url(r'^delete/list/', DeleteListView.as_view(), name="delete-list"),

    # Walmart APIs
    url(r'^walapi1', item_detail, name="item_detail"),
    url(r'^walapi2', upc, name="upc_search"),
    
    # Print URLs
    url(r'^print/', PrintListView.as_view(), name="print-list"),
    url(r'^printm/(?P<list_id>\d+)', PrintListMiniView.as_view(), name="print-m-list"),
]

fridgefiller/lists/models.py
from django.db import models
from django.conf import settings
from django.dispatch import receiver
from django.db.models.signals import post_save, pre_save, pre_delete
from django.contrib.auth.models import User

from datetime import datetime

import pytz

class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name="profile")
    name = models.CharField(max_length=32, default="")
    description = models.TextField(default="")
    lists = models.ManyToManyField('ShoppingList')

    def __str__(self):
        return str(self.name)

def create_user_profile(sender, instance, created, **kwargs):
    """
    Creates a UserProfile object for new users who sign up with allauth
    """
    if created:
        userprofile, created = UserProfile.objects.get_or_create(user=instance, name=instance.username)

post_save.connect(create_user_profile, sender=User)

def create_user_party(sender, instance, created, **kwargs):
    """
    Creates a Party object for Users that just contains themselves
    """
    if created:
        userparty, created = Party.objects.get_or_create(name=instance.name + "'s Personal Party", owner=instance)
        print "Created party for {}".format(instance.name)

post_save.connect(create_user_party, sender=UserProfile)

class Party(models.Model):
    name = models.CharField(max_length=32, default="")
    owner = models.ForeignKey('UserProfile', related_name="owner")
    users = models.ManyToManyField('UserProfile')
    shoppinglists = models.ManyToManyField('ShoppingList')


    def __str__(self):
        return str(self.name)

    def is_user_in_party(self, user):
        """
        Returns true if user is in the calling party, else false
        """
        return self.users.filter(pk=user.pk).exists()

    def add_party_member(self, receiver):
        try:
            self.users.add(receiver)
        except:
            return Http404("COULDN'T ADD " + receiver.name + " TO " + self.name)

    @models.permalink
    def get_absolute_url(self):
        return ('party', (), {'party_id': self.id})

    def get_from_url(self):
        return "/party/" + str(self.id) + "/"

def create_party_pantry(sender, instance, created, **kwargs):
    """
    Creates a Pantry object when a Party is saved
    """
    if created:
        partypantry, created = Pantry.objects.get_or_create(party=instance)
        print "Created pantry for {}".format(instance.name)

post_save.connect(create_party_pantry, sender=Party)


# Adds owner to group's user list if they aren't already in there
@receiver(post_save, sender=Party)
def add_owner_to_users(sender, instance, **kwargs):
    if not instance.owner in instance.users.all():
        instance.users.add(instance.owner)

class ShoppingList(models.Model):
    name = models.CharField(max_length=32, default="")
    owners = models.ManyToManyField('UserProfile', related_name="owners")
    description = models.TextField(default="")
    items = models.ManyToManyField('Item')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
       return str(self.name)

class Pantry(models.Model):
    items = models.ManyToManyField('ItemDetail', related_name='items')
    description = models.CharField(max_length=64, default="")
    party = models.ForeignKey('Party', related_name='party')

    def __str__(self):
        return str(self.party.name + "'s Pantry")

class Item(models.Model):
    name = models.CharField(max_length=64, default="")
    description = models.TextField(blank=True, default="")

    def __str__(self):
       return str(self.name)


# use default = null for optional stuff

class ItemDetail(models.Model):
    name = models.CharField(max_length=64, default="")
    description = models.TextField(blank=True, default="")
    cost = models.FloatField(default=0)
    last_purchased = models.DateTimeField(blank=True, default=datetime.min)
    location_purchased = models.CharField(max_length=64, blank=True, default="")
# barcode should be moved to its own entity once we gather what we need from it
    barcode = models.IntegerField(default=0, blank=True)
    unit = models.CharField(default=0, max_length=64)
    amount = models.FloatField(default=0)
    expiration_date = models.DateTimeField(blank=True, default=datetime.min)

    def get_cost(self):
        if self.cost == int(self.cost):
            self.cost = int(self.cost)

        if self.cost == 0:
            return "---"
        return self.cost

    def get_amount(self):
        if self.amount == int(self.amount):
            self.amount = int(self.amount)
        return self.amount

    def get_last_purchased(self):
        return self.last_purchased if self.last_purchased not in [datetime.min.replace(tzinfo=pytz.UTC), None] else "---"

    def get_expiration_date(self):
        return self.expiration_date if self.expiration_date not in [datetime.min.replace(tzinfo=pytz.UTC), None] else "---"

    def get_location_purchased(self):
        return self.location_purchased if self.location_purchased != "" else "---"

    def get_pretty_last_purchased(self):
        """
        Returns self.last_purchased as 'mm/dd/yyyy'
        """
        date_str = str(self.last_purchased.month) + "/" + str(self.last_purchased.day) + "/" + str(self.last_purchased.year)

        if date_str != "1/1/1":
            return date_str

        return ""

    def get_pretty_expiration_date(self):
        """
        Returns self.expiration_date as 'mm/dd/yyyy'
        """
        date_str = str(self.expiration_date.month) + "/" + str(self.expiration_date.day) + "/" + str(self.expiration_date.year)

        if date_str != "1/1/1":
            return date_str

        return ""



class Invitation(models.Model):
    class Meta:
        app_label = 'lists'
        ordering = ['-sent']

    RESPONSE_CHOICES = (('A', 'Accepted'),
                        ('D', 'Declined'))

    party = models.ForeignKey(Party)
    sender = models.ForeignKey(UserProfile, related_name="sent_invitations")
    receiver = models.ForeignKey(UserProfile, related_name="received_invitations")
    message = models.TextField()
    sent = models.DateTimeField(auto_now_add=True)
    read = models.BooleanField(default=False)
    response = models.CharField(blank=True, null=True, max_length=2,
                                choices=RESPONSE_CHOICES)

    @models.permalink
    def get_absolute_url(self):
        return ('invitation_detail', (), {'pk': self.pk})

    def __str__(self):
        return "%s invites %s to join %s" % (self.sender.name,
                                             self.receiver.name,
                                             self.party.name)

    def has_response(self):
        """Returns True if the receiver has responded, else False"""
        return self.response is not None

    def accept(self):
        """Accepts an invitation to join a team.
        Adds the invitation's recipient to the team. If the team is
        already full, throws an instance of TeamException """

        # If the user's already responded, don't let them respond again
        if self.has_response():
            return
        self.party.add_party_member(self.receiver)
        self.read = True
        self.response = 'A'     # Accepted
        self.save()

    def decline(self):
        """Declines an invitation to join a team.
        Just marks the invitation as declined"""
        # If the user's already responded, don't let them respond again
        if self.has_response():
            return
        self.read = True
        self.response = 'D'     # Declined
        self.save()

fridgefiller/lists/templates/lists/invitation/_accept_invitation_modal.html
{# This template requires: #}
{# id: The modal's id #}
{# title: The modal title #}
{# body: The modal body #}
{# warning: Adds a 'warning' section in red font (optional) #}
{# action: The URL to post "confirmed" to #}

<!-- Modal -->
<div id="{{ id }}" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">{{ title }}</h4>
      </div>
      <div class="modal-body text-center">
        <h4>Are you sure you want to join <span class="text-primary">{{ party }}</span>?</h4>
        {% if warning %}
          <p class="text-danger"><strong>WARNING:</strong> {{ warning }}</p>
        {% endif %}
      </div>
      <div class="modal-footer">
        <form action={{ action }} method="POST">
          {% csrf_token %}
          <input type="hidden" name="confirmed" value="true">
          <button type="button" class="btn btn-danger btn-lg pull-left" data-dismiss="modal">Cancel</button>
          <input class="btn btn-primary btn-lg pull-right" type="submit" value="Accept Invitation to {{ party }}">
        </form>
      </div>
    </div>
  </div>
</div>

fridgefiller/lists/templates/lists/invitation/_decline_invitation_modal.html
{# This template requires: #}
{# id: The modal's id #}
{# title: The modal title #}
{# body: The modal body #}
{# warning: Adds a 'warning' section in red font (optional) #}
{# action: The URL to post "confirmed" to #}

<!-- Modal -->
<div id="{{ id }}" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">{{ title }}</h4>
      </div>
      <div class="modal-body text-center">
        <h4>Are you sure you want to decline your invitation to join <span class="text-primary">{{ party }}</span>?
          <br><br>

          <span class="text-primary">{{ party.owner.name | title }}</span> will be <span class="text-danger">sad</span>!&nbsp;&nbsp;He or she really wanted you in this group!</h4>
        {% if warning %}
          <p class="text-danger"><strong>WARNING:</strong> {{ warning }}</p>
        {% endif %}
      </div>
      <div class="modal-footer">
        <form action={{ action }} method="POST">
          {% csrf_token %}
          <input type="hidden" name="confirmed" value="true">
          <button type="button" class="btn btn-danger btn-lg pull-left" data-dismiss="modal">Nope!&nbsp;&nbsp;Take me back, I don&apos;t want to upset {{ party.owner.name | title }}.</button>
          <input class="btn btn-primary btn-lg pull-right" type="submit" value="I'm sure">
        </form>
      </div>
    </div>
  </div>
</div>

fridgefiller/lists/templates/lists/invitation/_invitation_list.html
{% for invitation in invitations %}
  {% if forloop.first %}
    <div class="accordion" id="invite-accordion">
  {% endif %}

  <div class="panel panel-success">
    <div class="panel-heading" data-name="{{ name }}" id="panel-heading-{{ name }}-{{ counter }}"
         data-counter="{{ forloop.counter }}" data-toggle="collapse" data-target="{{ name }}Collapse{{ forloop.counter }}">
      <span id="{{ name }}-{{ forloop.counter }}-collapse-indicator" class="fa fa-plus primary"></span>&nbsp;&nbsp;
      <a>
         {% if invitation.receiver == user.profile %}
           Invitation from <strong>{{ invitation.sender }}</strong>
         {% else %}
           Invitation to <strong>{{ invitation.receiver }}</strong>
         {% endif %}

         to join <strong>{{ invitation.party.name }}</strong>

         {% if invitation.response %}
           {% ifequal invitation.response 'A' %}
             <span class="pull-right label label-primary">Accepted</span>
           {% endifequal %}
           {% ifequal invitation.response 'D' %}
             <span class="pull-right label label-danger">Declined</span>
           {% endifequal %}
         {% endif %}
         {% if not invitation.read %}
           <span id="unread-invite" class="label label-primary pull-right">Unread</span>
         {% endif %}
      </a>
    </div>
    <div id="{{ name }}Collapse{{ forloop.counter }}" class="panel-collapse">
      <div class="panel-body collapse" id="panel-body-{{ name }}-{{ forloop.counter }}">
        <p>
          {{ invitation.message }}
        </p>
        <div class="text-center">
          <a href="{{ invitation.get_absolute_url }}" class="btn btn-primary">Open Invitation</a>
        </div>
      </div>
    </div>
  </div>

  {% if forloop.last %}
    </div>
  {% endif %}

{% empty %}
  <h3 class="text-center"><i>No {{ name }} invitations.</i></h3>
{% endfor %}

{% block style %}
  <style type="text/css">
    span.fa {
      vertical-align: middle;
    }
    #unread-invite {
        vertical-align: -webkit-baseline-middle;
    }
    .panel-heading {
        -webkit-touch-callout: none;
        -webkit-user-select: none;
        -khtml-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
    }
  </style>
{% endblock %}

fridgefiller/lists/templates/lists/invitation/_modals.html
{% if invitation %}
  {% with party=invitation.party %}
    {# Accept modal #}
    {% url "invitation_accept" pk=invitation.pk as accept_invite %}

    {% include "lists/invitation/_accept_invitation_modal.html" with id="acceptInviteModal" title="Accept Invitation?" warning=warning action=accept_invite %}


    {# Decline modal #}
    {% url "invitation_decline" pk=invitation.pk as decline_invite %}

    {% include "lists/invitation/_decline_invitation_modal.html" with id="declineInviteModal" title="Decline Invitation?"  action=decline_invite %}

  {% endwith %}
{% endif %}

fridgefiller/lists/templates/lists/invitation/invitation_accept.html
{% extends "base.html" %}

{% block content %}
  {% url 'invitation_accept' competition.slug as form_action %}
  <form action="{{ form_action }}" class="form-horizontal" method="post">
    {% csrf_token %}

    {% for field in form %}
      <div class="control-group">
        <p>{{question}}</p>
        <label>{{ field.errors }}</label>

        <label class="checkbox">
          {{ field }} {{ field.label }}
        </label>
      </div>
    {% endfor %}

    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </form>
{% endblock %}

fridgefiller/lists/templates/lists/invitation/invitation_create.html
{% extends "base.html" %}

{% block title %}
    Create Invitation
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
  <br>
  {% if not form.fields.party.queryset.exists %}
    <span class="alert alert-danger"><strong>ERROR</strong>:&nbsp;&nbsp;You must&nbsp;<a href="{% url 'parties' %}">create a party</a>&nbsp;before you can send an invitation.</span>
    <br>
  {% endif %}

  {% crispy form %}

{% endblock %}

{% block style %}
  <style type="text/css">
      #id_receiver, #id_party {
        color: #fff;
        background-color: #1abc9c;
        width: auto;
        border: 1px #1abc9c solid;
        font-weight: bold;
      }
      #div_id_party, #div_id_receiver, #div_id_message {
          padding-left: 20px;
          padding-right: 20px;
      }
      #submit-id-submit {
          margin-left: 20px;
      }

      label  {
          padding-right: 20px;
          float: left;
      }
      .alert {
          display: flex;
      }
  </style>
{% endblock %}

{% block script %}
  <script type="text/javascript">
    $(document).ready(function() {
        {% if party %}
          // Append party name to invite header
          $('#invite-header').append(' to <span class="text-primary">{{ party.name }}</span>')

          // Select Party Name in dropdown for the user
          $('.select2-container option:contains({{ party.name }})').prop({selected: true});
        {% endif %}
    });
  </script>
{% endblock %}

fridgefiller/lists/templates/lists/invitation/invitation_decline.html
{% extends "base.html" %}

{% block content %}
  {% url 'invitation_accept' competition.slug as form_action %}
  <form action="{{ form_action }}" class="form-horizontal" method="post">
    {% csrf_token %}

    {% for field in form %}
      <div class="control-group">
        <p>{{question}}</p>
        <label>{{ field.errors }}</label>

        <label class="checkbox">
          {{ field }} {{ field.label }}
        </label>
      </div>
    {% endfor %}

    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Submit</button>
      </div>
    </div>
  </form>
{% endblock %}

fridgefiller/lists/templates/lists/invitation/invitation_detail.html
{% extends "base.html" %}

{% block page-header %}
  <div class="page-header">
    <h1>Invitation</h1>
  </div>
{% endblock %}

{% block content %}
  <h2 class="text-center" data-intro="This is a group invitation. If this invitation was sent to you, here you can accept or decline the invitation." data-step="1">Invitation to <a href="{{ invitation.party.get_absolute_url }}"><i>{{ invitation.party.name }}</i></a></h2>
  <div class="well">
    <div data-intro="Here you can see who sent the invitation and who the invitation was sent to, in addition to when it was sent" data-step="2">
    <p>
      <h3>
        <span>
          <strong>To:</strong> <span class="label label-inverse">{{ invitation.receiver }}</span>
        </span>
      </h3>
      &nbsp;&nbsp;&nbsp;
      <h3>
        <span>
          <strong>From:</strong> <span class="label label-primary">{{ invitation.sender }}</span>
        </span>
      </h3>
      <br><br>
      <span><strong>Sent:</strong> {{ invitation.sent }}</span><br>
    </p>
  </div>
    <hr>
    <h4>
      {{ invitation.message }}
    </h4>
    <br>

    {% if invitation.response == 'A' %} {# Accepted #}
      <a href="#" class="btn btn-success disabled">
        Accepted
      </a>
    {% endif %}

    {% if invitation.response == 'D' %} {# Declined #}
      <a href="#" class="btn btn-danger disabled">
        Declined
      </a>
    {% endif %}

    {% if not invitation.response and invitation.receiver == user.profile %}
      <div class="text-center" data-intro="You can use these buttons to respond to invitations you have received" data-step="3" data-position="top">
        <h5>Respond to this Invitation:</h5>
        <a data-toggle="modal" data-target="#acceptInviteModal" class="btn btn-success" href="#">
          Accept Invitation
        </a>
        <a data-toggle="modal" data-target="#declineInviteModal" class="btn btn-danger" href="#">
          Decline Invitation
        </a>
      </div>
    {% endif %}
  </div>
{% endblock %}

{% block modal %}
  {% include "lists/invitation/_modals.html" %}
{% endblock modal %}

{% block style %}
  <style type="text/css">
    h3 {
      display: inline;
    }
  </style>
{% endblock %}

fridgefiller/lists/templates/lists/invitation/invitation_list.html
{% extends "base.html" %}

{% block title %}
  Invitations
{% endblock %}

{% block page-header %}
  <div class="page-header">
    <h1>Your Invitations</h1>
  </div>
{% endblock %}

{% block content %}
  <div class="row" data-intro="This is your group invitations page! Here you can send and respond to invitations to groups!" data-step="1">
    <div class="col-sm-6 col-md-6" data-intro="This side of the page lists invitations you have recieved." data-step="2">
      <h2 class="text-center">Received Invitations</h2>
      {% include "lists/invitation/_invitation_list.html" with invitations=received name="received" %}

      <!-- Multiple pagers makes it hard to use the default pager :/ -->
      <div class="text-center">
        <div class="pagination text-center">
          <ul>
            <li class="previous {% if not received.has_previous %}disabled{% endif%}">
              {% if received.has_previous %}
                <a href="?received_page={{ received.previous_page_number }}&amp;sent_page={{ sent.number }}">
              {% else %}
                </a><a href="#">
              {% endif %}
              &larr; Previous
              </a>
            </li>
            <li class="next {% if not received.has_next %}disabled{% endif%}">
              {% if received.has_next %}
                <a href="?received_page={{ received.next_page_number }}&amp;sent_page={{ sent.number }}">
              {% else %}
                </a><a href="#">
              {% endif %}
              Next &rarr;
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-sm-6 col-md-6" data-intro="This side of the page lists invitations you have sent to other users." data-step="3">
      <h2 class="text-center">Sent Invitations</h2>
      {% include "lists/invitation/_invitation_list.html" with invitations=sent name="sent" %}

      <div class="text-center">
        <div class="pagination">
          <ul class="pager">
            <li class="previous {% if not sent.has_previous %}disabled{% endif%}">
              {% if sent.has_previous %}
                <a href="?sent_page={{ sent.previous_page_number }}&amp;received_page={{ received.number }}">
              {% else %}
                </a><a href="#">
              {% endif %}
              &larr; Previous
              </a>
            </li>
            <li class="next {% if not sent.has_next %}disabled{% endif%}">
              {% if sent.has_next %}
                <a href="?sent_page={{ sent.next_page_number }}&amp;received_page={{ received.number }}">
              {% else %}
                </a><a href="#">
              {% endif %}
              Next &rarr;
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <br>
  <div class="text-center">
    <a type="submit" data-intro="Click this button to send new invitations!" data-step="4" data-toggle="popover" data-placement="top" data-content="Create Invitations" class="btn btn-lg btn-primary" href="{% url 'invitation_create' %}">Invite User(s) to your Groups</a>

  </div>
{% endblock %}

{% block script %}
  <script type="text/javascript">
    $('.panel-heading').click(function() {
        var name = this.dataset.name;
        var counter = this.dataset.counter;

        // If collapsed, change plus to minus
        if($('#panel-body-' + name + '-' + counter).hasClass('collapse')) {
            $('#' + name + '-' + counter + '-collapse-indicator').removeClass('fa-plus')
            $('#' + name + '-' + counter + '-collapse-indicator').addClass('fa-minus')
        }
        // change minus to plus
        else {
            $('#' + name + '-' + counter + '-collapse-indicator').removeClass('fa-minus')
            $('#' + name + '-' + counter + '-collapse-indicator').addClass('fa-plus')
        }
        $('#panel-body-' + name + '-' + counter).toggleClass('collapse in')
    });
  </script>
{% endblock %}